SELECT
	IIF(ORDINAL_POSITION != 1, ', ', '')
	+ COLUMN_NAME
	+ ' '
	+ UPPER(DATA_TYPE)
	+ CASE
		WHEN CHARACTER_MAXIMUM_LENGTH IS NOT NULL THEN
			'(' + IIF(CHARACTER_MAXIMUM_LENGTH = -1, 'MAX', CONVERT(VARCHAR, CHARACTER_MAXIMUM_LENGTH)) + ')'
		WHEN NUMERIC_PRECISION IS NOT NULL AND NUMERIC_SCALE > 0 AND CHARINDEX('MONEY', DATA_TYPE) = 0 THEN
			'(' + CONVERT(VARCHAR, NUMERIC_PRECISION) + ', ' + CONVERT(VARCHAR, NUMERIC_SCALE) + ')'
		WHEN DATETIME_PRECISION IS NOT NULL AND DATA_TYPE != 'DATETIME' THEN
			'(' + CONVERT(VARCHAR, DATETIME_PRECISION) + ')'
		ELSE
			''
		END
FROM
	INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'mu_dummy'